name: 'Setup sci-cream Package'
description: 'Build and setup the sci-cream pnpm package using wasm-pack'
runs:
  using: 'composite'
  steps:
    - name: Build sci-cream package
      shell: bash
      run: pnpm --dir ./packages/sci-cream build:wasm && pnpm --dir ./packages/sci-cream build:js
