name: "Setup pnpm Environment"
description: "Setup pnpm and Install Dependencies"
inputs:
  working-directory:
    # Note that this is relative to the root of the repository.
    description: "Working directory to run pnpm install in"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: echo "pnpm_cache_dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install pnpm dependencies
      shell: bash
      run: pnpm --dir ${{ inputs.working-directory }} install
